### ISSUE TITLE
failed: [503] Service Unavailable while running the bot in node js, bot framework emulator

### ISSUE THREAD

**Issue by anjalirathore** [MicrosoftDocs/bot-framework-docs#47]
Hi, I am buiding a bot using MS bot framework in node js. After changing some proxy settings (as it was required due to intranet network), it is throwing following error - 
Error: Request to 'http://localhost:65031/v3/botstate/emulator/conversations/6j7gi25fe43a' failed: [503] Service Unavailable
    at Request._callback (c:\luis_bot\node_modules\botbuilder\lib\bots\ChatConnector.js:523:46)
    at Request.self.callback (c:\luis_bot\node_modules\botbuilder\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (c:\luis_bot\node_modules\botbuilder\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (c:\luis_bot\node_modules\botbuilder\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)

why I am getting this and how to fix it.
[app.zip](https://github.com/MicrosoftDocs/bot-framework-docs/files/1266707/app.zip)

**Comment by szul** [comment]
You might consider asking this on StackOverflow, or posting it as an issue in Microsoft's [BotBuilder](https://github.com/Microsoft/BotBuilder) repository, which is the home of the SDK's.
